name: manual action

on:
  workflow_dispatch

jobs:

  jobA:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Greet
        run: echo "Hi, this is a manual test"

      - name: Secret value
        run: echo ${{ secrets.SECRET_GREETING }}