name: publish

on:
  # Runs the workflow automatically after the build/test workflow is COMPLETED
  workflow_run:
    workflows: ["build/test"]
    types:
      - "completed"
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: dotnetdemoapi
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Set this to the path to your web app project, defaults to the repository root:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: |
          cd src/Web
          dotnet build -c Release --no-restore
          dotnet publish -c Release -o ../dotnet-webapp -r linux-x64 --self-contained true /p:UseAppHost=true

      - name: Test
        run: |
          cd test/Web
          dotnet test --no-restore --verbosity normal

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/dotnet-webapp'

      