name: First Cron Job

on:
  schedule:
    # *(minute (0-59)) *(hour (0-23)) *(day of the month (1-31)) *(month (1-12)) *(day of the week (0-6))
    - cron: "*/5 * * * *"

jobs:
  cron:
    
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run : echo Hello, world!
